
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
      - OPSWAT_API_KEY=${OPSWAT_API_KEY}
    restart: always
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/package.json


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json

